#!/usr/bin/python3

import random

print('Password Generator')

chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@$%^&*()~`-_.,?1234567890'

number = input('Number of Passwords:')
number = int(number)

lenght = input('Password Lenght:')
lenght = int(lenght)

print('\nHere are your passwords:')

for passwd in range(number):
    passwords = ''
    for c in range(lenght):
      passwords += random.choice(chars)
    print(passwords)
      
