#!/usr/bin/python3

import random

print('Password Generator')

chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@$%^&*()~`-_.,?1234567890'

number = input('Number of Passwords:')
number = int(number)

length = input('Password Length:')
length = int(length)

print('\nHere are your passwords:')

for passwd in range(number):
    passwords = ''
    for c in range(length):
      passwords += random.choice(chars)
    print(passwords)
      
